title: Ignasius J. Simbolon
subtitle: >-
  Software Engineer / Developer from Indonesia.
domain: ignasius-j-s.github.io
url: https://ignasius-j-s.github.io
baseurl: ""
email: ignis19@protonmail.com
github: "https://github.com/ignasius-j-s"
permalink: /blog/:categories/:title/

sass:
  sass_dir: _sass

defaults:
  - scope:
      type: posts
    values:
      layout: post
      author: Ignasius
      lang: en

author: Ignasius

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
  - LICENSE
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

footer:
  links:
    - label: "GitHub"
      icon: "fa-brands fa-fw fa-github"
      url: "https://github.com/ignasius-j-s"
